import React, { useState } from 'react';
import { AnalysisResult, Severity, LogEvent, PlaybookResponse, Incident } from '../types';
import { TimelineChart, AttackDistributionChart, SeverityChart, GeoDistributionChart, LogTypeChart } from './Charts';
import LogTable from './LogTable';
import PlaybookPanel from './PlaybookPanel';
import { generatePlaybook } from '../services/geminiService';
import { ShieldAlert, ShieldCheck, Activity, Terminal, TrendingUp, TrendingDown, Minus, FileText } from 'lucide-react';

interface DashboardProps {
  data: AnalysisResult;
  onReset: () => void;
  onCreateIncident?: (incident: Incident) => void;
}

const Dashboard: React.FC<DashboardProps> = ({ data, onReset, onCreateIncident }) => {
  // Playbook State
  const [isPlaybookOpen, setIsPlaybookOpen] = useState(false);
  const [playbookLoading, setPlaybookLoading] = useState(false);
  const [playbookError, setPlaybookError] = useState<string | null>(null);
  const [currentPlaybook, setCurrentPlaybook] = useState<PlaybookResponse | null>(null);

  const handleRunPlaybook = async (event: LogEvent) => {
    setIsPlaybookOpen(true);
    setPlaybookLoading(true);
    setPlaybookError(null);
    setCurrentPlaybook(null);
    try {
      const playbook = await generatePlaybook(event);
      setCurrentPlaybook(playbook);
    } catch (err: any) {
      console.error("Failed to generate playbook", err);
      setPlaybookError("Unable to generate playbook. Please ensure your API Key is configured correctly.");
    } finally {
      setPlaybookLoading(false);
    }
  };

  const getRiskColor = (score: number) => {
    if (score >= 80) return "text-red-500";
    if (score >= 50) return "text-orange-500";
    if (score >= 20) return "text-amber-400";
    return "text-emerald-400";
  };

  const getRiskLabel = (score: number) => {
    if (score >= 80) return "CRITICAL RISK";
    if (score >= 50) return "HIGH RISK";
    if (score >= 20) return "MEDIUM RISK";
    return "LOW RISK";
  };

  return (
    <div className="w-full max-w-7xl mx-auto space-y-8 pb-12">
      
      {/* Playbook Overlay */}
      {isPlaybookOpen && (
        <PlaybookPanel 
          playbook={currentPlaybook} 
          isLoading={playbookLoading}
          error={playbookError}
          onClose={() => setIsPlaybookOpen(false)} 
        />
      )}

      {/* Header Actions */}
      <div className="flex justify-between items-center bg-slate-900 border border-slate-800 p-4 rounded-xl">
         <div>
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
                <FileText className="text-blue-500" size={24} />
                Forensic Analysis Report
            </h2>
            <p className="text-xs text-slate-400">Deep dive insights generated by Gemini AI</p>
         </div>
         <button 
          onClick={onReset}
          className="bg-slate-800 hover:bg-slate-700 text-slate-200 px-4 py-2 rounded-lg text-sm font-medium transition-colors"
        >
          Upload New Log
        </button>
      </div>

      <div className="space-y-6">
            {/* Risk Score & Baseline Metrics */}
            <div className="flex flex-col xl:flex-row gap-6">
                
                {/* Risk Score Card */}
                <div className="flex-none xl:w-1/4 bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl relative overflow-hidden group hover:border-slate-700 transition-colors">
                    <div className="absolute top-0 right-0 p-3 opacity-10 group-hover:opacity-20 transition-opacity">
                        <ShieldAlert size={120} />
                    </div>
                    <h2 className="text-slate-400 text-xs font-bold uppercase tracking-wider mb-2">Security Posture Score</h2>
                    <div className="flex items-end gap-4 relative z-10">
                        <span className={`text-6xl font-bold ${getRiskColor(data.riskScore)}`}>
                        {data.riskScore}
                        </span>
                        <div className="flex flex-col mb-2">
                        <span className={`text-xl font-bold ${getRiskColor(data.riskScore)} opacity-50`}>
                            / 100
                        </span>
                        <span className={`text-xs font-bold px-2 py-0.5 rounded-full bg-slate-950 border border-slate-800 ${getRiskColor(data.riskScore)}`}>
                            {getRiskLabel(data.riskScore)}
                        </span>
                        </div>
                    </div>
                    <div className="mt-4 pt-4 border-t border-slate-800">
                            <div className="w-full bg-slate-950 rounded-full h-1.5 overflow-hidden">
                            <div 
                                className={`h-full rounded-full ${data.riskScore > 50 ? 'bg-red-500' : 'bg-emerald-500'}`} 
                                style={{ width: `${data.riskScore}%` }}
                            ></div>
                            </div>
                    </div>
                </div>

                {/* Baseline Metrics Grid */}
                <div className="flex-grow grid grid-cols-2 md:grid-cols-4 gap-4">
                    {data.baselineMetrics?.map((metric, idx) => (
                        <div key={idx} className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex flex-col justify-between shadow-lg hover:border-slate-700 transition-colors">
                            <div className="flex justify-between items-start mb-2">
                                <span className="text-slate-500 text-[10px] font-bold uppercase tracking-wider truncate pr-2">{metric.label}</span>
                                {metric.status === 'critical' ? <TrendingUp size={16} className="text-red-500 shrink-0" /> : 
                                metric.status === 'warning' ? <TrendingUp size={16} className="text-orange-500 shrink-0" /> :
                                metric.status === 'good' ? <TrendingDown size={16} className="text-emerald-500 shrink-0" /> :
                                <Minus size={16} className="text-slate-500 shrink-0" />}
                            </div>
                            <span className="text-2xl font-bold text-slate-100 truncate">{metric.value}</span>
                            {metric.subtext && <span className="text-xs text-slate-500 mt-1 truncate">{metric.subtext}</span>}
                        </div>
                    ))}
                    {/* Fallback Static Stats if no baseline metrics */}
                    {(!data.baselineMetrics || data.baselineMetrics.length === 0) && (
                        <>
                            <StatCard label="Total Events" value={data.events.length} icon={<Activity size={20} className="text-blue-400"/>} />
                            <StatCard label="Critical Threats" value={data.events.filter(e => e.severity === Severity.CRITICAL).length} icon={<ShieldAlert size={20} className="text-red-500"/>} />
                            <StatCard label="Unique Sources" value={new Set(data.events.map(e => e.source)).size} icon={<Terminal size={20} className="text-amber-400"/>} />
                            <StatCard label="Clean Events" value={data.events.filter(e => e.severity === Severity.LOW).length} icon={<ShieldCheck size={20} className="text-emerald-400"/>} />
                        </>
                    )}
                </div>
            </div>

            {/* Executive Summary */}
            <div className="bg-slate-900/50 border border-slate-800/50 rounded-xl p-6 relative">
                    <div className="absolute top-0 left-0 w-1 h-full bg-blue-500/20 rounded-l-xl"></div>
                    <h3 className="text-slate-400 text-xs font-bold uppercase tracking-wider mb-2 flex items-center gap-2">
                    <FileText size={14} /> AI Executive Summary
                    </h3>
                    <p className="text-slate-300 leading-relaxed text-sm font-medium">
                    {data.summary}
                    </p>
            </div>

            {/* Charts Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg xl:col-span-2">
                    <TimelineChart data={data.timelineData} />
                </div>
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg">
                    <SeverityChart events={data.events} />
                </div>
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg">
                    <GeoDistributionChart data={data.geoData || []} />
                </div>
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg">
                    <LogTypeChart data={data.logTypes || []} />
                </div>
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg">
                    <AttackDistributionChart data={data.topAttackTypes} />
                </div>
            </div>

            {/* Detailed Table */}
            <LogTable events={data.events} onRunPlaybook={handleRunPlaybook} onCreateIncident={onCreateIncident} />
        </div>
    </div>
  );
};

const StatCard: React.FC<{ label: string; value: number; icon: React.ReactNode; highlight?: boolean }> = ({ label, value, icon, highlight }) => (
  <div className={`bg-slate-900 border rounded-xl p-4 flex flex-col justify-between shadow-lg transition-all
    ${highlight ? 'border-red-500/50 bg-red-500/5' : 'border-slate-800 hover:border-slate-700'}
  `}>
    <div className="flex justify-between items-start mb-2">
      <span className="text-slate-500 text-xs font-semibold uppercase">{label}</span>
      {icon}
    </div>
    <span className="text-2xl font-bold text-slate-100">{value}</span>
  </div>
);

export default Dashboard;