import React from 'react';
import { PlaybookResponse } from '../types';
import { Terminal, Ticket, Mail, Copy, Check, X, AlertTriangle } from 'lucide-react';

interface PlaybookPanelProps {
  playbook: PlaybookResponse | null;
  isLoading: boolean;
  error?: string | null;
  onClose: () => void;
}

const PlaybookPanel: React.FC<PlaybookPanelProps> = ({ playbook, isLoading, error, onClose }) => {
  const [copiedIndex, setCopiedIndex] = React.useState<number | null>(null);

  const handleCopy = (content: string, index: number) => {
    navigator.clipboard.writeText(content);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  if (!playbook && !isLoading && !error) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div className="w-full max-w-2xl bg-slate-900 border border-slate-700 rounded-xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]">
        
        {/* Header */}
        <div className="p-4 border-b border-slate-800 flex justify-between items-center bg-slate-950">
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <span className={`w-2 h-2 rounded-full ${error ? 'bg-red-500' : 'bg-emerald-500'}`}></span>
            AI Security Playbook
          </h3>
          <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors">
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center h-64 space-y-4">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-emerald-500"></div>
              <p className="text-slate-400 text-sm animate-pulse">Generating remediation strategy...</p>
            </div>
          ) : error ? (
            <div className="flex flex-col items-center justify-center h-64 space-y-4 text-center">
               <div className="p-4 bg-red-500/10 rounded-full border border-red-500/20 text-red-400">
                  <AlertTriangle size={32} />
               </div>
               <div className="space-y-2">
                   <h3 className="text-white font-medium">Generation Failed</h3>
                   <p className="text-slate-400 text-sm max-w-xs mx-auto">{error}</p>
               </div>
               <button onClick={onClose} className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded text-sm transition-colors">
                  Close
               </button>
            </div>
          ) : playbook ? (
            <>
              <div className="space-y-2">
                <h2 className="text-xl font-bold text-white">{playbook.title}</h2>
                <p className="text-slate-400 text-sm leading-relaxed">{playbook.description}</p>
              </div>

              <div className="space-y-4">
                {playbook.actions.map((action, idx) => (
                  <div key={idx} className="bg-slate-950 border border-slate-800 rounded-lg overflow-hidden">
                    <div className="px-4 py-3 border-b border-slate-800 bg-slate-900/50 flex justify-between items-center">
                      <div className="flex items-center gap-2">
                        {action.type === 'CLI' && <Terminal size={16} className="text-emerald-400" />}
                        {action.type === 'TICKET' && <Ticket size={16} className="text-blue-400" />}
                        {action.type === 'EMAIL' && <Mail size={16} className="text-amber-400" />}
                        <span className="text-sm font-medium text-slate-200">{action.label}</span>
                      </div>
                      <button 
                        onClick={() => handleCopy(action.content, idx)}
                        className="text-xs flex items-center gap-1 text-slate-500 hover:text-slate-300 transition-colors"
                      >
                        {copiedIndex === idx ? <Check size={14} className="text-emerald-500" /> : <Copy size={14} />}
                        {copiedIndex === idx ? "Copied" : "Copy"}
                      </button>
                    </div>
                    <div className="p-4 overflow-x-auto">
                      <pre className="text-sm font-mono text-slate-300 whitespace-pre-wrap leading-relaxed">
                        {action.content}
                      </pre>
                    </div>
                  </div>
                ))}
              </div>
            </>
          ) : null}
        </div>

        {/* Footer */}
        {!error && !isLoading && (
            <div className="p-4 border-t border-slate-800 bg-slate-950 text-xs text-slate-500 flex justify-between">
                <span>Generated by Gemini 2.5 Flash</span>
                <span className="text-orange-500/80">Review all commands before execution.</span>
            </div>
        )}
      </div>
    </div>
  );
};

export default PlaybookPanel;